version: '3'
services:

  db:
    image : postgres
    restart: always
   

    environment:
      POSTGRES_PASSWORD: theroot
      POSTGRES_USER: sims
      POSTGRES_DB: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
  app:
    image: japp
    restart: always
    ports:
      - 4000:4000  
